### ISSUE TITLE
v2 tag

### ISSUE THREAD

**Issue by woodsaj** [raintank/schema#19]
the latest pushed tag is 1.6 at https://github.com/raintank/schema/commit/c068e0c9c054af19c858b2d947741180c09ea6b1

Since then we have merged some significant changes and need to create a new tag so that imports via gopkg.in work correctly.

The changes made are not backwards compatible, (clients can send data using a v1 tag to a server server using master, but clients using master cant send to a server using v1.6).
So we need to create a v2 tag

**Comment by Dieterbe** [comment]
done. though note, in MT we switched to dep and stopped using gopkg.in
it's much simpler and allows for this cleanup as well https://github.com/raintank/schema/pull/21
