### ISSUE TITLE
KeyBySeries appends series name after pre-existing content within buf

### ISSUE THREAD

**Issue by Dieterbe** [raintank/schema#8]
instead of
```
func (m *MetricDefinition) KeyBySeries(b []byte) []byte {
       b = append(b, []byte(m.Name)...)
       return b
}
```
I think we should do
```
func (m *MetricDefinition) KeyBySeries(b []byte) []byte {
       b = append(b[:0], []byte(m.Name)...)
       return b
}
```

by using `b[:0]` we create a new slice with len 0, but reusing the same allocated backing array (and so the capacity stays the same too)

**Comment by woodsaj** [comment]
I disagree.  It is not up to KeyBySeries to determine if it should reset the slice.  The caller should do that.  If they really want to just append the key to an existing slice they should be able to.  This is how every other function i have seen that accepts an initial byte slice works.  eg. msgp.MarshalMsg()

**Comment by Dieterbe** [comment]
you're right.
