### ISSUE TITLE
KeyByOrgId incorrect

### ISSUE THREAD

**Issue by Dieterbe** [raintank/schema#9]
```
func (m *MetricDefinition) KeyByOrgId(b []byte) []byte {
       if len(b) < 4 {
               b = append(b, make([]byte, 4-len(b))...)
       }
       binary.LittleEndian.PutUint32(b, uint32(m.OrgId))
       return b
}
```

I see 3 problems:
1) if `len(b)` > 4, then there will be arbitrary pre-existing data that remains as part of the key
2) this allocates a new slice based on the length, though `b` may have plenty of capacity, which is the important consideration wrt allocations and slice reuse
3) potentially allocates twice: once for the `4-len(b)` sized one, and again when appending this one to b when b doesn't have the capacity.

I'm not sure yet what's the best, most elegant, fastest solution.

**Comment by Dieterbe** [comment]
https://groups.google.com/forum/m/#!topic/golang-nuts/ETbw1ECDgRs I like the solution by "rog"

**Comment by woodsaj** [comment]
i think we can just make this.
```
func  (m *MetricDefinition) KeyByOrgId(b []byte) []byte {
	if cap(b)-len(b) < 4 {
		// not enough unused space in the slice so we need to grow it.
		newBuf := make([]byte, len(b), len(b)+4)
		copy(newBuf, b)
		b = newBuf
	}
	// PutUint32 writes directly to the slice rather then appending.
        // so we need to set the length to 4 more bytes then it currently is.
	b = b[:len(b)+4]
	binary.LittleEndian.PutUint32(b[len(b)-4:], uint32(m.OrgId))
	return b
}
```

The 2 main use cases are:
1) pass an empty slice. either nil or make([]byte, 0)
* cap and len are both 0. So we create a new slice with len=0 and cap=4
* we then set the len to 4 and write the uint32

2) re-use a slice with len=0 and cap>=4
* cap(b) - len(b) is > 4
* set the len to 4 and write the uint32

if the user sends in a slice with len >0 then the uint32 will be appended.

**Comment by Dieterbe** [comment]
ah right, we want to append to pre-existing data by design, ok sounds good.

your suggested code looks solid to me.
